name: CMake

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - "Makefile.mingw"
      - "Makefile.msvc"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - "Makefile.mingw"
      - "Makefile.msvc"
  workflow_dispatch:

env:
  LUAROCKS_WINDOWS_DEPS_DIR: C:\external
  LIBLZMA_WINDOWS_VERSION: 5.8.1

jobs:

  cmake-build:
    name: CMake Build
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: pwsh

    strategy:
      fail-fast: false

      matrix:

        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - luajit
          - openresty

        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

        is-msvc:
          - true
          - false

        exclude:
          - os: ubuntu-latest
            is-msvc: true
          - os: macos-latest
            is-msvc: true

    steps:

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: lua-xz

      - name: Restore liblzma tarball
        id: restore-liblzma-tarball
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: xz-${{ env.LIBLZMA_WINDOWS_VERSION }}.tar.gz
          key: xz-${{ env.LIBLZMA_WINDOWS_VERSION }}

      - name: Download liblzma tarball
        if: ${{ steps.restore-liblzma-tarball.outputs.cache-hit != 'true' }}
        run: curl -kLO "https://github.com/tukaani-project/xz/releases/download/v${{ env.LIBLZMA_WINDOWS_VERSION }}/xz-${{ env.LIBLZMA_WINDOWS_VERSION }}.tar.gz"

      - name: Save liblzma tarball
        if: ${{ steps.restore-liblzma-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: xz-${{ env.LIBLZMA_WINDOWS_VERSION }}.tar.gz
          key: xz-${{ env.LIBLZMA_WINDOWS_VERSION }}

      - name: Extract liblzma and set environment variables for the build
        run: |
          $tarball = Join-Path -Path "${{ github.workspace }}" -ChildPath "xz-${{ env.LIBLZMA_WINDOWS_VERSION }}.tar.gz";
          Copy-Item -Path "${tarball}" -Destination "${{ runner.temp }}" | Out-Null;
          cd "${{ runner.temp }}";
          tar -xf "xz-${{ env.LIBLZMA_WINDOWS_VERSION }}.tar.gz";
          if ($LASTEXITCODE -eq 0)
          {
            $extracted_dir = Join-Path -Path "${{ runner.temp }}" -ChildPath "xz-${{ env.LIBLZMA_WINDOWS_VERSION }}";
            Add-Content "${{ github.env }}" "LIBLZMA_CUSTOM_SOURCE_DIR=${extracted_dir}";
          }
          else
          {
            Write-Host "Failed to extract ${tarball}";
            exit 1;
          }

      - name: Setup MSVC dev-prompt
        if: ${{ runner.os == 'Windows' && matrix.is-msvc }}
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

      - name: Configure, build and install liblzma
        run: |
          if ("${{ runner.os }}" -eq "macOS")
          {
            cd "${{ env.LIBLZMA_CUSTOM_SOURCE_DIR }}";
            ./configure && `
            make && `
            sudo make install;
          }
          else
          {
            $build_dir = Join-Path -Path "${{ runner.temp }}" -ChildPath "build-liblzma";
            $cmake_generator = "Unix Makefiles";
            $install_prefix = "/usr/local";

            if ("${{ runner.os }}" -eq "Windows")
            {
              $install_prefix = "${{ env.LUAROCKS_WINDOWS_DEPS_DIR }}";
              if ($${{ matrix.is-msvc }})
              {
                $cmake_generator = "NMake Makefiles";
              }
              else
              {
                $cmake_generator = "MinGW Makefiles";
              }
            }

            cmake `
              -G "${cmake_generator}" `
              "-DCMAKE_BUILD_TYPE=Release" `
              "-DBUILD_SHARED_LIBS=ON" `
              --install-prefix "${install_prefix}" `
              -S "${{ env.LIBLZMA_CUSTOM_SOURCE_DIR }}" `
              -B "${build_dir}" && `
            cmake --build "${build_dir}" --config Release;

            if ($LASTEXITCODE -eq 0)
            {
              if ("${{ runner.os }}" -eq "Windows")
              {
                cmake --install "${build_dir}" --config "Release";
              }
              else
              {
                sudo cmake --install "${build_dir}" --config "Release" && `
                sudo ldconfig;
              }
            }
            else
            {
              Write-Host "Failed to build liblzma";
              exit 1;
            }
          }

      - name: On Windows, make liblzma available to CMake
        if: ${{ runner.os == 'Windows' }}
        run: |
          $cmake_prefix_path = "$env:CMAKE_PREFIX_PATH";
          Add-Content "${{ github.env }}" "CMAKE_PREFIX_PATH=${cmake_prefix_path};${{ env.LUAROCKS_WINDOWS_DEPS_DIR }}";

      - name: Setup Lua
        uses: luau-project/setup-lua@4598c69e67a91a1621b5ab4aed54fd9ab82c3508 # v1.0.3
        with:
          lua-version: ${{ matrix.lua-version }}
          luarocks-version: none

      - name: Configure lua-xz
        run: |
          $build_dir = Join-Path -Path "${{ runner.temp }}" -ChildPath "build-lua-xz";
          $cmake_generator = "Unix Makefiles";
          $install_prefix = Join-Path -Path "${{ github.workspace }}" -ChildPath ".lua";

          if ("${{ runner.os }}" -eq "Windows")
          {
            if ($${{ matrix.is-msvc }})
            {
              $cmake_generator = "NMake Makefiles";
            }
            else
            {
              $cmake_generator = "MinGW Makefiles";
            }
          }

          cmake `
            -G "${cmake_generator}" `
            "-DCMAKE_BUILD_TYPE=Release" `
            "-DLUA_VERSION=${{ matrix.lua-version }}" `
            --install-prefix "${install_prefix}" `
            -S "lua-xz" `
            -B "${build_dir}" && `
          Add-Content "${{ github.env }}" "LUA_XZ_CUSTOM_BUILD_DIR=${build_dir}";

      - name: Build lua-xz
        run: cmake --build "${{ env.LUA_XZ_CUSTOM_BUILD_DIR }}" --config "Release"

      - name: Test lua-xz
        run: ctest --test-dir "${{ env.LUA_XZ_CUSTOM_BUILD_DIR }}" -C "Release"

      - name: Install lua-xz
        run: cmake --install "${{ env.LUA_XZ_CUSTOM_BUILD_DIR }}" --config "Release"
